#! /bin/sh

bspc rule -r "*"

sxhkd &
$GOPATH/bin/btops &

bspc monitor DP-2 -d 1
bspc monitor HDMI-2 -d 2
bspc monitor HDMI-1 -d 3

bspc desktop -f 1

bspc config border_width 0
bspc config window_gap 0
bspc config top_padding 0
bspc config focus_follows_pointer true

dropdownname="dropdown"
bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
bspc rule -a St:$dropdownname hidden=on
bspc rule -a St:$dropdownname sticky=on
bspc rule -a St:$dropdownname state=floating

bspc config external_rules_command "$(which floaters)"

# pointer
#xsetroot -cursor_name left_ptr
bspc config pointer_follows_focus true

bspc rule -a scratchpad sticky=on state=floating hidden=on
$TERM -c scratchpad -e ~/.local/bin/scratch &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
