#! /bin/sh

bspc rule -r "*"

sxhkd &

bspc monitor DP-2 -d 1
bspc monitor HDMI-2 -d 2
bspc monitor HDMI-1 -d 3

bspc desktop -f 1

bspc config border_width 3
bspc config window_gap 15
bspc config top_padding 20
bspc config focus_follows_pointer true

dropdownname="dropdown"
bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
bspc rule -a St:$dropdownname hidden=on
bspc rule -a St:$dropdownname sticky=on
bspc rule -a St:$dropdownname state=floating

bspc config external_rules_command "$(which floaters)"
